import { GithubIssuesService } from '../service';

describe('getUniqueMembers', () => {
  it('should return unique member', async () => {
    const members = [
      {
        login: 'merjoontest1',
        id: 179820065,
        node_id: 'U_kgDOCrfWIQ',
        avatar_url: 'https://avatars.githubusercontent.com/u/179820065?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/merjoontest1',
        html_url: 'https://github.com/merjoontest1',
        followers_url: 'https://api.github.com/users/merjoontest1/followers',
        following_url: 'https://api.github.com/users/merjoontest1/following{/other_user}',
        gists_url: 'https://api.github.com/users/merjoontest1/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/merjoontest1/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/merjoontest1/subscriptions',
        organizations_url: 'https://api.github.com/users/merjoontest1/orgs',
        repos_url: 'https://api.github.com/users/merjoontest1/repos',
        events_url: 'https://api.github.com/users/merjoontest1/events{/privacy}',
        received_events_url: 'https://api.github.com/users/merjoontest1/received_events',
        type: 'User',
        user_view_type: 'public',
        site_admin: false,
      },
      {
        login: 'merjoontest22',
        id: 185327983,
        node_id: 'U_kgDOCwvhbw',
        avatar_url: 'https://avatars.githubusercontent.com/u/185327983?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/merjoontest22',
        html_url: 'https://github.com/merjoontest22',
        followers_url: 'https://api.github.com/users/merjoontest22/followers',
        following_url: 'https://api.github.com/users/merjoontest22/following{/other_user}',
        gists_url: 'https://api.github.com/users/merjoontest22/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/merjoontest22/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/merjoontest22/subscriptions',
        organizations_url: 'https://api.github.com/users/merjoontest22/orgs',
        repos_url: 'https://api.github.com/users/merjoontest22/repos',
        events_url: 'https://api.github.com/users/merjoontest22/events{/privacy}',
        received_events_url: 'https://api.github.com/users/merjoontest22/received_events',
        type: 'User',
        user_view_type: 'public',
        site_admin: false,
      },
      {
        login: 'merjoontest1',
        id: 179820065,
        node_id: 'U_kgDOCrfWIQ',
        avatar_url: 'https://avatars.githubusercontent.com/u/179820065?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/merjoontest1',
        html_url: 'https://github.com/merjoontest1',
        followers_url: 'https://api.github.com/users/merjoontest1/followers',
        following_url: 'https://api.github.com/users/merjoontest1/following{/other_user}',
        gists_url: 'https://api.github.com/users/merjoontest1/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/merjoontest1/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/merjoontest1/subscriptions',
        organizations_url: 'https://api.github.com/users/merjoontest1/orgs',
        repos_url: 'https://api.github.com/users/merjoontest1/repos',
        events_url: 'https://api.github.com/users/merjoontest1/events{/privacy}',
        received_events_url: 'https://api.github.com/users/merjoontest1/received_events',
        type: 'User',
        user_view_type: 'public',
        site_admin: false,
      },
    ];
    const uniqueMembers = GithubIssuesService.getUniqueMembers(members);
    expect(uniqueMembers).toEqual([
      {
        login: 'merjoontest1',
        id: 179820065,
        node_id: 'U_kgDOCrfWIQ',
        avatar_url: 'https://avatars.githubusercontent.com/u/179820065?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/merjoontest1',
        html_url: 'https://github.com/merjoontest1',
        followers_url: 'https://api.github.com/users/merjoontest1/followers',
        following_url: 'https://api.github.com/users/merjoontest1/following{/other_user}',
        gists_url: 'https://api.github.com/users/merjoontest1/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/merjoontest1/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/merjoontest1/subscriptions',
        organizations_url: 'https://api.github.com/users/merjoontest1/orgs',
        repos_url: 'https://api.github.com/users/merjoontest1/repos',
        events_url: 'https://api.github.com/users/merjoontest1/events{/privacy}',
        received_events_url: 'https://api.github.com/users/merjoontest1/received_events',
        type: 'User',
        user_view_type: 'public',
        site_admin: false,
      },
      {
        login: 'merjoontest22',
        id: 185327983,
        node_id: 'U_kgDOCwvhbw',
        avatar_url: 'https://avatars.githubusercontent.com/u/185327983?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/merjoontest22',
        html_url: 'https://github.com/merjoontest22',
        followers_url: 'https://api.github.com/users/merjoontest22/followers',
        following_url: 'https://api.github.com/users/merjoontest22/following{/other_user}',
        gists_url: 'https://api.github.com/users/merjoontest22/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/merjoontest22/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/merjoontest22/subscriptions',
        organizations_url: 'https://api.github.com/users/merjoontest22/orgs',
        repos_url: 'https://api.github.com/users/merjoontest22/repos',
        events_url: 'https://api.github.com/users/merjoontest22/events{/privacy}',
        received_events_url: 'https://api.github.com/users/merjoontest22/received_events',
        type: 'User',
        user_view_type: 'public',
        site_admin: false,
      },
    ]);
  });
});
